### ISSUE TITLE
Does Not appear to be a valid canari package

### ISSUE THREAD

**Issue by JohnnyNoMates** [catalyst256/Watcher#4]
Hi Following you install instructions i receive this error:

Looking for transforms in Watcher...
Traceback (most recent call last):
  File "/usr/local/bin/canari", line 4, in <module>
    **import**('pkg_resources').run_script('canari==3.0', 'canari')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/EGG-INFO/scripts/canari", line 22, in <module>
    canari_main()
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/common.py", line 61, in canari_main
    opts.command_function(opts)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/create_profile.py", line 57, in create_profile
    transform_package = TransformDistribution(opts.package)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/pkgutils/transform.py", line 68, in **init**
    (self.name, self.name, e))
ImportError: Does not appear to be a valid canari package. Couldn't import the 'Watcher.transforms' package in 'Watcher'. Error message: cannot import name configure

You help would be gratefully received.

**Comment by catalyst256** [comment]
Hello, based on the error reporting I think it's because canari 3.0 is installed and the original transforms were built around canari 1.1 I will have a look over the next couple of days to see if I can migrate them across.

**Comment by JohnnyNoMates** [comment]
Hi, that would be great, fingers crossed
Thanks again for looking into it.
